/**
 * @fileoverview Sous-composants pour l'onglet de création d'article
 * Contient les éléments de formulaire pour la création d'un nouvel article.
 *
 * @module components/stock/StockItemCreateForm
 * @requires react
 * @requires prop-types
 * @requires @radix-ui/themes
 * @requires lucide-react
 */

import PropTypes from "prop-types";
import { Flex, Box, Button, TextField, Text, Select } from "@radix-ui/themes";
import { Plus } from "lucide-react";

// ===== CONSTANTS =====
const UNIT_OPTIONS = [
  { value: "pcs", label: "Pièces" },
  { value: "m", label: "Mètres" },
  { value: "kg", label: "Kg" },
  { value: "l", label: "Litres" },
  { value: "boite", label: "Boîte" },
  { value: "rouleau", label: "Rouleau" },
];

/**
 * Contenu de l'onglet de création d'article
 * @component
 * @private
 * @param {Object} props - Props du formulaire de création
 * @param {string} props.newItemName - Nom de l'article
 * @param {Function} props.onNewItemNameChange - Callback nom
 * @param {string} props.newItemFamilyCode - Code famille
 * @param {Function} props.onNewItemFamilyCodeChange - Callback famille
 * @param {string} props.newItemSubFamilyCode - Code sous-famille
 * @param {Function} props.onNewItemSubFamilyCodeChange - Callback sous-famille
 * @param {string} props.newItemSpec - Spécification
 * @param {Function} props.onNewItemSpecChange - Callback spec
 * @param {string} props.newItemDimension - Dimension
 * @param {Function} props.onNewItemDimensionChange - Callback dimension
 * @param {string} props.newItemUnit - Unité
 * @param {Function} props.onNewItemUnitChange - Callback unité
 * @param {string} props.newItemLocation - Localisation
 * @param {Function} props.onNewItemLocationChange - Callback localisation
 * @param {Array} props.subFamilies - Sous-familles disponibles
 * @param {Array} props.stockFamilies - Familles de stock
 * @param {string} props.autoGeneratedRef - Référence auto-générée
 * @param {Function} props.onCreateItem - Callback création
 * @param {boolean} props.isFormValid - Formulaire valide
 * @param {boolean} [props.loading=false] - État de chargement
 * @returns {JSX.Element} Formulaire de création
 */
export function CreateTabContent({
  newItemName,
  onNewItemNameChange,
  newItemFamilyCode,
  onNewItemFamilyCodeChange,
  newItemSubFamilyCode,
  onNewItemSubFamilyCodeChange,
  newItemSpec,
  onNewItemSpecChange,
  newItemDimension,
  onNewItemDimensionChange,
  newItemUnit,
  onNewItemUnitChange,
  newItemLocation,
  onNewItemLocationChange,
  subFamilies,
  stockFamilies,
  autoGeneratedRef,
  onCreateItem,
  isFormValid,
  loading,
}) {
  return (
    <Flex direction="column" gap="3">
      {/* Item name */}
      <TextField.Root
        placeholder="Nom de l'article *"
        value={newItemName}
        onChange={(e) => onNewItemNameChange(e.target.value)}
        size="2"
      />

      {/* Family & SubFamily */}
      <Flex gap="2">
        <Box style={{ flex: 1 }}>
          <Text size="2" color="gray" mb="1" style={{ display: "block" }}>
            Famille *
          </Text>
          <Select.Root
            value={newItemFamilyCode}
            onValueChange={onNewItemFamilyCodeChange}
            size="2"
          >
            <Select.Trigger placeholder="Sélectionner..." />
            <Select.Content>
              {stockFamilies.map((family) => (
                <Select.Item key={family.code} value={family.code}>
                  {family.label}
                </Select.Item>
              ))}
            </Select.Content>
          </Select.Root>
        </Box>

        <Box style={{ flex: 1 }}>
          <Text size="2" color="gray" mb="1" style={{ display: "block" }}>
            Sous-famille *
          </Text>
          <Select.Root
            value={newItemSubFamilyCode}
            onValueChange={onNewItemSubFamilyCodeChange}
            disabled={!newItemFamilyCode}
            size="2"
          >
            <Select.Trigger placeholder="Sélectionner..." />
            <Select.Content>
              {subFamilies.map((subFamily) => (
                <Select.Item key={subFamily.code} value={subFamily.code}>
                  {subFamily.label}
                </Select.Item>
              ))}
            </Select.Content>
          </Select.Root>
        </Box>
      </Flex>

      {/* Spec & Dimension */}
      <Flex gap="2">
        <TextField.Root
          placeholder="Spécification (optionnel)"
          value={newItemSpec}
          onChange={(e) => onNewItemSpecChange(e.target.value)}
          size="2"
          style={{ flex: 1 }}
        />
        <TextField.Root
          placeholder="Dimension *"
          value={newItemDimension}
          onChange={(e) => onNewItemDimensionChange(e.target.value)}
          size="2"
          style={{ flex: 1 }}
        />
      </Flex>

      {/* Unit & Location */}
      <Flex gap="2">
        <Box style={{ flex: 1 }}>
          <Text size="2" color="gray" mb="1" style={{ display: "block" }}>
            Unité
          </Text>
          <Select.Root value={newItemUnit} onValueChange={onNewItemUnitChange} size="2">
            <Select.Trigger />
            <Select.Content>
              {UNIT_OPTIONS.map((option) => (
                <Select.Item key={option.value} value={option.value}>
                  {option.label}
                </Select.Item>
              ))}
            </Select.Content>
          </Select.Root>
        </Box>

        <TextField.Root
          placeholder="Localisation"
          value={newItemLocation}
          onChange={(e) => onNewItemLocationChange(e.target.value)}
          size="2"
          style={{ flex: 1 }}
        />
      </Flex>

      {/* Auto-generated reference */}
      <Box>
        <Text size="1" color="gray" style={{ display: "block", marginBottom: "4px" }}>
          Référence auto-générée : <strong>{autoGeneratedRef}</strong>
        </Text>
      </Box>

      {/* Submit button */}
      <Button onClick={onCreateItem} disabled={!isFormValid || loading} size="2">
        <Plus size={16} />
        {loading ? "Création..." : "Créer et lier"}
      </Button>
    </Flex>
  );
}

CreateTabContent.propTypes = {
  newItemName: PropTypes.string.isRequired,
  onNewItemNameChange: PropTypes.func.isRequired,
  newItemFamilyCode: PropTypes.string.isRequired,
  onNewItemFamilyCodeChange: PropTypes.func.isRequired,
  newItemSubFamilyCode: PropTypes.string.isRequired,
  onNewItemSubFamilyCodeChange: PropTypes.func.isRequired,
  newItemSpec: PropTypes.string.isRequired,
  onNewItemSpecChange: PropTypes.func.isRequired,
  newItemDimension: PropTypes.string.isRequired,
  onNewItemDimensionChange: PropTypes.func.isRequired,
  newItemUnit: PropTypes.string.isRequired,
  onNewItemUnitChange: PropTypes.func.isRequired,
  newItemLocation: PropTypes.string.isRequired,
  onNewItemLocationChange: PropTypes.func.isRequired,
  subFamilies: PropTypes.array.isRequired,
  stockFamilies: PropTypes.arrayOf(
    PropTypes.shape({
      code: PropTypes.string,
      label: PropTypes.string,
    })
  ).isRequired,
  autoGeneratedRef: PropTypes.string.isRequired,
  onCreateItem: PropTypes.func.isRequired,
  isFormValid: PropTypes.bool.isRequired,
  loading: PropTypes.bool,
};
