import {
  Home,
  LogIn,
  Wrench,
  ClipboardList,
  ClipboardCheck,
  Factory,
  Package,
  ShoppingCart,
  Database,
  Activity,
  Truck,
  Settings,
  CalendarClock,
} from 'lucide-react';

export const PAGES_CONFIG = [
  // ── Auth ──────────────────────────────────────────────────────────────────
  {
    id: 'login',
    path: '/login',
    label: 'Connexion',
    icon: LogIn,
    pageTitle: 'Connexion',
    pageSubtitle: 'Connectez-vous à votre compte',
    publicOnly: true,
    requiresAuth: false,
    showInMenu: false,
  },

  // ── Main ──────────────────────────────────────────────────────────────────
  {
    id: 'home',
    path: '/',
    label: 'Accueil',
    icon: Home,
    pageTitle: 'Accueil',
    pageSubtitle: "Bienvenue dans l'application GMAO",
    section: 'main',
    requiresAuth: true,
    showInMenu: true,
    order: 0,
  },

  // ── Maintenance ───────────────────────────────────────────────────────────
  {
    id: 'briefing',
    path: '/briefing',
    label: 'Briefing',
    icon: ClipboardList,
    pageTitle: 'Briefing',
    pageSubtitle: 'Situations actives et décisions en attente',
    section: 'maintenance',
    requiresAuth: true,
    order: 15,
  },
  {
    id: 'interventions',
    path: '/interventions',
    label: 'Interventions',
    icon: Wrench,
    pageTitle: 'Interventions',
    pageSubtitle: 'Gestion des interventions de maintenance',
    section: 'maintenance',
    requiresAuth: true,
    order: 10,
  },
  {
    id: 'intervention-requests',
    path: '/intervention-requests',
    label: 'Demandes',
    icon: ClipboardList,
    pageTitle: "Demandes d'intervention",
    pageSubtitle: "Suivi des demandes avant création d'intervention",
    section: 'maintenance',
    requiresAuth: true,
    order: 15,
    showInMenu: false,
  },
  {
    id: 'equipements',
    path: '/equipements',
    label: 'Équipements',
    icon: Factory,
    pageTitle: 'Gestion des Équipements',
    pageSubtitle: "Parc d'équipements avec état de santé et classification",
    section: 'maintenance',
    requiresAuth: true,
    order: 20,
  },
  {
    id: 'preventive',
    path: '/preventive',
    label: 'Préventif',
    icon: ClipboardCheck,
    pageTitle: 'Préventif',
    pageSubtitle: 'Plans et occurrences de maintenance préventive',
    section: 'maintenance',
    requiresAuth: true,
    order: 40,
  },

  // ── Stock ─────────────────────────────────────────────────────────────────
  {
    id: 'stock',
    path: '/stock',
    label: 'Stock',
    icon: Package,
    pageTitle: 'Stock',
    pageSubtitle: 'Pièces référencées et familles',
    section: 'stock',
    requiresAuth: true,
    order: 30,
  },
  {
    id: 'purchase-requests',
    path: '/achats',
    label: "Demandes d'achat",
    icon: ShoppingCart,
    pageTitle: "Demandes d'achat",
    pageSubtitle: "Gestion et dispatch des demandes d'achat",
    section: 'stock',
    requiresAuth: true,
    order: 40,
  },
  {
    id: 'suppliers',
    path: '/suppliers',
    label: 'Fournisseurs',
    icon: Truck,
    pageTitle: 'Fournisseurs',
    pageSubtitle: 'Répertoire et liaisons pièces',
    section: 'stock',
    requiresAuth: true,
    showInMenu: false,
  },

  // ── Production ────────────────────────────────────────────────────────────
  {
    id: 'service-status',
    path: '/service-status',
    label: 'État du service',
    icon: Activity,
    pageTitle: 'État du service',
    pageSubtitle: 'Charge, fragmentation, capacité réelle',
    section: 'production',
    requiresAuth: true,
  },
  {
    id: 'quality-data',
    path: '/quality-data',
    label: 'Qualité Données',
    icon: Database,
    pageTitle: 'Qualité des données',
    pageSubtitle: 'Contrôle de complétude et cohérence',
    section: 'production',
    requiresAuth: true,
  },

  // ── Admin ─────────────────────────────────────────────────────────────────
  {
    id: 'admin',
    path: '/admin',
    label: 'Administration',
    icon: Settings,
    pageTitle: 'Administration',
    pageSubtitle: 'Utilisateurs, rôles, référentiel et sécurité',
    section: 'admin',
    requiresAuth: true,
    showInMenu: true,
    requiredRoles: ['RESP', 'ADMIN'],
    order: 0,
  },
  {
    id: 'admin-preventive-plans',
    path: '/admin/preventive-plans',
    label: 'Plans Préventifs',
    icon: ClipboardCheck,
    pageTitle: 'Plans Préventifs',
    pageSubtitle: 'Configuration de la maintenance préventive',
    section: 'admin',
    requiresAuth: true,
    order: 10,
    showInMenu: false,
  },
  {
    id: 'admin-preventive-occurrences',
    path: '/admin/preventive-occurrences',
    label: 'Occurrences Préventives',
    icon: CalendarClock,
    pageTitle: 'Occurrences Préventives',
    pageSubtitle: 'Génération et suivi des occurrences de maintenance',
    section: 'admin',
    requiresAuth: true,
    order: 20,
    showInMenu: false,
  },
];
